services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yii_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ../base:/var/www/base
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii_db
    restart: always
    command: --lower_case_table_names=1
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data: